/* Generated by Yosys 0.65 (git sha1 b85cad634-dirty, aarch64-linux-android-clang++ 13989888, -fstack-protector-strong -Oz -fPIC -O3) */

module riscv_core(clk, rst, instr, pc);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input instr;
  wire instr;
  output pc;
  wire pc;
  assign pc = 1'h0;
endmodule
