/* Generated by Yosys 0.65 (git sha1 b85cad634-dirty, aarch64-linux-android-clang++ 13989888, -fstack-protector-strong -Oz -fPIC -O3) */

module fpu_ieee754(clk, a, b);
  input clk;
  wire clk;
  input a;
  wire a;
  input b;
  wire b;
endmodule
